[package]
name = "obs-focused"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
obws="0.12.0"
tokio={version="1.9.0",features=["full"]}
windows = {version="0.58",features=["UI","Win32_UI_WindowsAndMessaging"]}
serde_json ="1"
